const iconsMap = {
  "Sunny": "wi-day-sunny",
  "Clear": "wi-night-clear",
  "Partly Cloudy": "wi-day-cloudy",
  "Cloudy": "wi-cloudy",
  "Overcast": "wi-cloudy",
  "Mist": "wi-fog",
  "Patchy rain possible": "wi-showers",
  "Patchy snow possible": "wi-snow",
  "Patchy sleet possible": "wi-sleet",
  "Patchy freezing drizzle possible": "wi-sleet",
  "Thundery outbreaks possible": "wi-thunderstorm",
  "Blowing snow": "wi-snow-wind",
  "Blizzard": "wi-snow-wind",
  "Fog": "wi-fog",
  "Freezing fog": "wi-fog",
  "Patchy light drizzle": "wi-raindrops",
  "Light drizzle": "wi-raindrops",
  "Freezing drizzle": "wi-raindrops",
  "Heavy freezing drizzle": "wi-raindrops",
  "Patchy light rain": "wi-rain",
  "Light rain": "wi-rain",
  "Moderate rain at times": "wi-rain",
  "Moderate rain": "wi-rain",
  "Heavy rain at times": "wi-rain-wind",
  "Heavy rain": "wi-rain-wind",
  "Light freezing rain": "wi-sleet",
  "Moderate or heavy freezing rain": "wi-sleet",
  "Light sleet": "wi-sleet",
  "Moderate or heavy sleet": "wi-sleet",
  "Patchy light snow": "wi-snow",
  "Light snow": "wi-snow",
  "Patchy moderate snow": "wi-snow",
  "Moderate snow": "wi-snow",
  "Patchy heavy snow": "wi-snow-wind",
  "Heavy snow": "wi-snow-wind",
  "Ice pellets": "wi-hail",
  "Light rain shower": "wi-showers",
  "Moderate or heavy rain shower": "wi-showers",
  "Torrential rain shower": "wi-showers",
  "Light sleet showers": "wi-sleet",
  "Moderate or heavy sleet showers": "wi-sleet",
  "Light snow showers": "wi-snow",
  "Moderate or heavy snow showers": "wi-snow",
  "Light showers of ice pellets": "wi-hail",
  "Moderate or heavy showers of ice pellets": "wi-hail",
  "Patchy light rain with thunder": "wi-storm-showers",
  "Moderate or heavy rain with thunder": "wi-thunderstorm",
  "Patchy light snow with thunder": "wi-storm-showers",
  "Moderate or heavy snow with thunder": "wi-thunderstorm",
};

export default iconsMap;